print(123)
print("Hello,world")
print(123+456)
print("Hello,Python")
print(123+456)
print("Hello,Python")
for i in range(1):
    print(i)
print("what is your name?")
name = input()
print("your name is " + name)